# -*- coding: utf-8 -*-
"""3D_object.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-G46ZKf4cHSA_t73xRHOKSTE82nVpoN1

<a href="https://colab.research.google.com/github/labviros/computer-vision-topics/blob/version2020/lesson03-camera_model/3D_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3D Object

## Transforming 3D points

Create and use Rigid Body Motion Transformations to change the object
"""

# Commented out IPython magic to ensure Python compatibility.
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# %matplotlib inline

# load points
points = np.loadtxt('box.xyz').T
points = np.vstack((points,np.ones(points.shape[1])))
fig = plt.figure(figsize=[10,10])
ax0 = plt.axes(projection='3d')
ax0.set_title('3D points')
ax0.set_xlabel('x-axis')
ax0.set_ylabel('y-axis')
ax0.set_zlabel('z-axis')
ax0.set_xlim([-2,2])
ax0.set_ylim([-1,1])
ax0.set_zlim([4,8])

ax0.plot3D(points[0,:],points[1,:],points[2,:],'k.')
ax0.view_init(elev=45,azim=-45)
plt.show()